### ISSUE TITLE
Edition #102 (Week 1/2) Submissions

### ISSUE THREAD

**Issue by irshadpc** [pedrommcarrasco/CocoaHub.content#231]

**Comment by irshadpc** [comment]
Availability checks

https://www.swiftbysundell.com/basics/availability/

**Comment by irshadpc** [comment]
Customizing how an external Swift type is encoded or decoded

https://www.swiftbysundell.com/articles/customizing-how-a-type-is-encoded-or-decoded/

**Comment by irshadpc** [comment]
Connecting async/await to other Swift code

https://www.swiftbysundell.com/articles/connecting-async-await-with-other-swift-code/

**Comment by irshadpc** [comment]
Creating 3D Models from Photographs with RealityKit in Swift

https://swiftrocks.com/creating-3d-models-out-of-anything-with-realitykit-in-swift

**Comment by irshadpc** [comment]
Backport SwiftUI safe area insets to iOS 13 and 14

https://www.fivestars.blog/articles/safe-area-insets-2/

**Comment by irshadpc** [comment]
Mastering search in SwiftUI

https://swiftwithmajid.com/2021/06/23/mastering-search-in-swiftui/

**Comment by irshadpc** [comment]
Making SwiftUI views refreshable

https://www.swiftbysundell.com/articles/making-swiftui-views-refreshable/

**Comment by peterfriese** [comment]
Getting Started with async/await in SwiftUI

https://peterfriese.dev/swiftui-concurrency-essentials-part1/

(Twitter handle: @peterfriese)
