### ISSUE TITLE
Edition #102 (Week 2/2) Submissions

### ISSUE THREAD

**Issue by irshadpc** [pedrommcarrasco/CocoaHub.content#232]
# Submissions:
- N/A

# Curators
- N/A

**Comment by irshadpc** [comment]
How to use a flexible frame in SwiftUI

https://onmyway133.com/posts/how-to-use-flexible-frame-in-swiftui/

**Comment by irshadpc** [comment]
Dismissing a SwiftUI modal or detail view

https://swiftbysundell.com/articles/dismissing-swiftui-modal-and-detail-views/

**Comment by irshadpc** [comment]
Optional SwiftUI views

https://swiftbysundell.com/tips/optional-swiftui-views/

**Comment by irshadpc** [comment]
Actors in Swift: how to use and prevent data races

https://www.avanderlee.com/swift/actors/

**Comment by irshadpc** [comment]
The many faces of button in SwiftUI

https://swiftwithmajid.com/2021/06/30/the-many-faces-of-button-in-swiftui/

**Comment by irshadpc** [comment]
Using UISheetPresentationController in SwiftUI

https://www.donnywals.com/using-uisheetpresentationcontroller-in-swiftui/

**Comment by zntfdr** [comment]
SwiftUI patterns evolution: view builders

https://www.fivestars.blog/articles/swiftui-patterns-view-builders/

**Comment by irshadpc** [comment]
Swift Concurrency by Example

https://www.hackingwithswift.com/quick-start/concurrency

**Comment by irshadpc** [comment]
Highlights of SwiftUI Release 3

https://rudrank.blog/highlights-swiftui-3

**Comment by pedrommcarrasco** [comment]
Advanced SwiftUI Animations — Part 4: TimelineView

https://swiftui-lab.com/swiftui-animations-part4
