### ISSUE TITLE
Edition #103 Submissions (Part 1)

### ISSUE THREAD

**Issue by irshadpc** [pedrommcarrasco/CocoaHub.content#234]
# Submissions:
- N/A

# Curators
- N/A

**Comment by irshadpc** [comment]
Meet the new Button styling

https://www.fivestars.blog/articles/button-styles-2/

**Comment by irshadpc** [comment]
MainActor usage in Swift explained to dispatch to the main thread

https://www.avanderlee.com/swift/mainactor-dispatch-main-thread

**Comment by irshadpc** [comment]
Mutating and non-mutating Swift contexts

https://swiftbysundell.com/articles/mutating-and-nonmutating-swift-contexts/

**Comment by irshadpc** [comment]
Mastering AsyncImage in SwiftUI

https://swiftwithmajid.com/2021/07/07/mastering-asyncimage-in-swiftui/

**Comment by irshadpc** [comment]
SwiftUI: Bridging UIKit with ScrollViewReader and DragGesture

https://www.fivestars.blog/articles/section-title-index-swiftui/

**Comment by irshadpc** [comment]
Diffable data source behavior changes and reconfiguring cells in iOS 15

https://www.jessesquires.com/blog/2021/07/08/diffable-data-source-behavior-changes-and-reconfiguring-cells-in-ios-15/

**Comment by irshadpc** [comment]
Protocols in Gradient and Chroma Game

https://rudrank.blog/protocols-in-gradient-game

**Comment by irshadpc** [comment]
How to add an AppDelegate and a SceneDelegate to a SwiftUI app

https://www.fivestars.blog/articles/app-delegate-scene-delegate-swiftui/

**Comment by irshadpc** [comment]
Stroking and filling a SwiftUI shape at the same time

https://www.swiftbysundell.com/articles/stroking-and-filling-a-swiftui-shape-at-the-same-time/

**Comment by irshadpc** [comment]
Experimenting with ShazamKit- Let’s Shazam Everything!

https://rudrank.blog/experimenting-with-shazamkit

**Comment by zntfdr** [comment]
Environment Objects and SwiftUI Styles

https://www.fivestars.blog/articles/environment-objects-and-swiftui-styles/

**Comment by zntfdr** [comment]
Backporting new features with @_alwaysEmitIntoClient

https://www.fivestars.blog/articles/alwaysEmitIntoClient
