### ISSUE TITLE
Editions #25 Submissions

### ISSUE THREAD

**Issue by pedrommcarrasco** [pedrommcarrasco/CocoaHub.content#25]
# Submissions:
- https://medium.com/better-programming/creating-an-apple-like-splash-screen-in-swiftui-fdeb36b47e81 - Submitted by [Irshad PC](https://twitter.com/_irshadpc)
- https://medium.com/swlh/integrating-swiftui-with-uikit-and-developing-xcode-previews-for-uikits-viewcontroller-39941aaf2392 - Submitted by [Irshad PC](https://twitter.com/_irshadpc)
- https://bryce.co/recreating-imessage-confetti/ - Submitted by [Pedro Carrasco](https://twitter.com/pedrommcarrasco)
- https://swiftbysundell.com/articles/lightweight-api-design-in-swift/ - Submitted by [Pedro Carrasco](https://twitter.com/pedrommcarrasco)
- https://www.donnywals.com/deciding-where-to-store-data/ - Submitted by [Pedro Carrasco](https://twitter.com/pedrommcarrasco)
- https://www.vadimbulavin.com/modern-networking-in-swift-5-with-urlsession-combine-framework-and-codable/ - Submitted by [Vadim Bulavin](https://twitter.com/V8tr)
- https://medium.com/flawless-app-stories/the-perfect-ios-app-architecture-4e3d1ab96fa4 - Submitted by [Irshad PC](https://twitter.com/_irshadpc)
- https://www.avanderlee.com/swift/operations/ - Submitted by [Irshad PC](https://twitter.com/_irshadpc)
- https://pspdfkit.com/blog/2019/intro-cpp-swift-developers/ - Submitted by [Irshad PC](https://twitter.com/_irshadpc)
- https://www.donnywals.com/adding-haptics-to-your-app/ - Submitted by [Irshad PC](https://twitter.com/_irshadpc)
- https://swiftwithmajid.com/2019/11/27/combine-and-swiftui-views/ - Submitted by [Irshad PC](https://twitter.com/_irshadpc)
- https://lickability.com/blog/how-our-engineers-collaborate/ - Submitted by [Pedro Carrasco](https://twitter.com/pedrommcarrasco)
https://increment.com/teams/the-path-to-management/ - Submitted by [Pedro Carrasco](https://twitter.com/pedrommcarrasco)

# Curators
- [Irshad PC](https://twitter.com/_irshadpc)
- [Pedro Carrasco](https://twitter.com/pedrommcarrasco)
- [Vadim Bulavin](https://twitter.com/V8tr)

##### To submit a new article and become a curator, please post it here. Only articles from November 22 to November 29.

**Comment by irshadpc** [comment]
Creating an Apple-like Splash Screen in SwiftUI.


https://medium.com/better-programming/creating-an-apple-like-splash-screen-in-swiftui-fdeb36b47e81

**Comment by irshadpc** [comment]
Integrating SwiftUI with UIKit and Developing Xcode Previews for UIKit’s ViewController


https://link.medium.com/2evCgcwmQ1

**Comment by pedrommcarrasco** [comment]
Recreating iMessage Confetti

https://bryce.co/recreating-imessage-confetti/

**Comment by pedrommcarrasco** [comment]
Lightweight API design in Swift

https://swiftbysundell.com/articles/lightweight-api-design-in-swift/

**Comment by pedrommcarrasco** [comment]
Deciding where to store data

https://www.donnywals.com/deciding-where-to-store-data/

**Comment by V8tr** [comment]
Hi @pedrommcarrasco, I hope you are OK if I suggest my own article here 🙂

[Modern Networking in Swift 5 with URLSession, Combine and Codable](https://www.vadimbulavin.com/modern-networking-in-swift-5-with-urlsession-combine-framework-and-codable/)

**Comment by pedrommcarrasco** [comment]
It's perfectly fine @V8tr 👍

**Comment by irshadpc** [comment]
The perfect iOS app architecture


https://medium.com/flawless-app-stories/the-perfect-ios-app-architecture-4e3d1ab96fa4

**Comment by irshadpc** [comment]
Getting started with Operations and OperationQueues in Swift

https://www.avanderlee.com/swift/operations/

**Comment by irshadpc** [comment]
Introduction to C++ for Swift Developers


https://pspdfkit.com/blog/2019/intro-cpp-swift-developers/

**Comment by irshadpc** [comment]
Adding Haptics to your app

https://www.donnywals.com/adding-haptics-to-your-app/

**Comment by pedrommcarrasco** [comment]
@irshadpc on 🔥 (as usual!)

**Comment by irshadpc** [comment]
Combine and SwiftUI views

https://swiftwithmajid.com/2019/11/27/combine-and-swiftui-views/

**Comment by irshadpc** [comment]
Getting started with Operations and OperationQueues in Swift


https://www.avanderlee.com/swift/operations/

**Comment by pedrommcarrasco** [comment]
How Our Engineers Collaborate

https://increment.com/teams/the-path-to-management/

**Comment by pedrommcarrasco** [comment]
The path to management

https://increment.com/teams/the-path-to-management/

**Comment by pedrommcarrasco** [comment]
Thanks to everyone who contributed 👍
