### ISSUE TITLE
Newsletters & Podcasts Submissions

### ISSUE THREAD

**Issue by pedrommcarrasco** [pedrommcarrasco/CocoaHub.content#76]
Hey 👋

### Announcement
Since the public beta announcement CocoaHub has been sharing every issue/episode of the following newsletters/podcasts:
- **iOS Dev Weekly** (Newsletter)
- **Swift Weekly Brief** (Newsletter)
- **The Swift Community Podcast** (Podcast)
- **Stacktrace** (Podcast)
- **Swift by Sundell** (Podcast)

We are now looking to expand this list with 2 or 3 new items and we would love to know which ones you would like to see included.

### Rules
- There's no restriction in how many items you can vote
- To vote, simply react with a 👍 on the item/s of your choice
- You can add new items by commenting like I did
- Do **not** add newsletters focused in sharing personal content.

**Comment by pedrommcarrasco** [comment]
**iOS Goodies** (Newsletter)
https://ios-goodies.com/

**Comment by pedrommcarrasco** [comment]
**Contravariance (Podcast)**
https://contravariance.rocks/

**Comment by pedrommcarrasco** [comment]
**Launched** (Podcast)
https://launchedfm.com/

**Comment by pedrommcarrasco** [comment]
**Swift over Coffee** (Podcast)
https://anchor.fm/swiftovercoffee

**Comment by pedrommcarrasco** [comment]
**Swift Unwrapped** (Podcast)
https://spec.fm/podcasts/swift-unwrapped

**Comment by bobek-balinek** [comment]
**Waiting for Review** (Podcast)
https://www.waitingforreview.com

**Comment by jonjon1251** [comment]
Everyday Robots (Podcast) 

https://everydayrobots.tech

**Comment by crsantos** [comment]
**Under the Radar** (Podcast)

[https://www.relay.fm/radar](https://www.relay.fm/radar)

**Comment by pedrommcarrasco** [comment]
Thanks to everyone who voted and/or shared new podcasts and newsletters.
We'll be adding **iOS Goodies**, **Swift Over Coffee** and **Contravariance** to our list of Podcasts/Newsletters
